### ISSUE TITLE
Doesn't work with ST3 and Markdown Preview

### ISSUE THREAD

**Issue by rr326** [dz0ny/LiveReload-sublimetext2#106]
It seems like LiveReload is abandonware, but maybe this note will save some others some time.

I'm pretty sure LiveReload doesn't work with ST3 and Markdown Preview.  I've wasted a lot of time trying to configure it, but I think it just doesn't work. Instead, try Markdown Preview and the [LiveReload App](http://feedback.livereload.com/knowledgebase/articles/67441-how-do-i-start-using-livereload)

FYI - here's a trace from my console window in ST3

	INFO:WebSocketClient:Command: hello
	ERROR:WebSocketClient:receive error
	Traceback (most recent call last):
	  File "/Users/rrosen/Library/Application Support/Sublime Text 3/Packages/LiveReload/server/WebSocketClient.py", line 274, in onreceive
	    self.handler.updateInfo()
	  File "/Users/rrosen/Library/Application Support/Sublime Text 3/Packages/LiveReload/server/WebSocketServer.py", line 25, in updateInfo
	    self.server.clients_info.append(client.info)
	AttributeError: 'WebSocketClient' object has no attribute 'info'

	...

	INFO:WebSocketClient:Remove from clients table <LiveReload.server.WebSocketClient.WebSocketClient object at 0x110302d10>
	ERROR:WebSocketClient:WebSocket error
	Traceback (most recent call last):
	  File "/Users/rrosen/Library/Application Support/Sublime Text 3/Packages/LiveReload/server/WebSocketClient.py", line 84, in __init__
	    data = self.socket.recv(1024)
	OSError: [Errno 9] Bad file descriptor

**Comment by LeonardoGentile** [comment]
Indeed I have the same problem
