### ISSUE TITLE
Dose not support Sublime Text 3 on Windows 7 64bit

### ISSUE THREAD

**Issue by nanking** [dz0ny/LiveReload-sublimetext2#110]
Hello 
I was frustrated when i have been installed devel on ST3.
here is what i got exception below
Traceback (most recent call last):
  File "C:\Editor\Sublime Text Build 3083 x64\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Editor\Sublime Text Build 3083 x64\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "livereload_st2 in C:\Editor\Sublime Text Build 3083 x64\Data\Installed Packages\LiveReload.sublime-package", line 21
    except Exception, u:
                    ^
SyntaxError: invalid syntax

**Comment by nanking** [comment]
please drop this issue that because this error was my configuration faults,i am so sorry deeply

**Comment by Arty2** [comment]
@nanking How did you fix this issue? It appears to be common with ST3 users.
